import { create } from "xmlbuilder2";
import { useNuxtApp } from "#app";

class XmlHelper {
  constructor(organizationSettings, courseType, course) {
    this.organizationSettings = organizationSettings;
    this.courseType = courseType;
    this.course = course;
    const { $supabase } = useNuxtApp();
    this.supabase = $supabase;
  }

  async fetchLocations(locationIds) {
    const { data, error } = await this.supabase
      .from("places")
      .select("*")
      .in("id", locationIds);
    if (error) {
      console.error("Error fetching locations:", error);
      return [];
    }
    return data;
  }

  async fetchStartTimes(startTimeIds) {
    const { data, error } = await this.supabase
      .from("start_times")
      .select("*")
      .in("id", startTimeIds);
    if (error) {
      console.error("Error fetching start times:", error);
      return [];
    }
    return data;
  }

  async fetchDates(dateIds) {
    const { data, error } = await this.supabase
      .from("dates")
      .select("*")
      .in("id", dateIds);
    if (error) {
      console.error("Error fetching dates:", error);
      return [];
    }
    return data;
  }

  async calculateCombinations() {
    const locations = await this.fetchLocations(this.course.location_ids);
    const startTimes = await this.fetchStartTimes(this.course.start_time_ids);
    const dates = await this.fetchDates(this.course.dates_ids);
    const titles = this.course.titles;
    const types = this.course.types;

    const combinations = [];
    for (const location of locations) {
      for (const startTime of startTimes) {
        for (const date of dates) {
          for (const title of titles) {
            for (const type of types) {
              const combination = { location, startTime, date, title, type };
              combinations.push(combination);
              console.log("einzelne kombination", combination);
            }
          }
        }
      }
    }

    console.log(`Total combinations: ${combinations.length}`);
    return combinations;
  }

  async generateXml() {
    const combinations = await this.calculateCombinations();

    // Create the XML document
    const root = create({
      version: "1.0",
      encoding: "iso-8859-15",
      standalone: "yes",
    })
      .ele("OPENQCAT", {
        version: "1.1",
        "xsi:noNamespaceSchemaLocation": "openQ-cat.V1.1.xsd",
        "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
      })
      .ele("HEADER")
      .ele("GENERATOR_INFO")
      .txt("Export OpenQ 3.45.0")
      .up()
      .ele("CATALOG")
      .ele("LANGUAGE")
      .txt("deu")
      .up()
      .ele("CATALOG_ID")
      .txt("90037-1719216329353")
      .up()
      .ele("CATALOG_VERSION")
      .txt("Vers_KURSNET")
      .up()
      .ele("CATALOG_NAME")
      .txt("KURSNET-Export")
      .up()
      .ele("GENERATION_DATE")
      .txt("2024-06-24T10:05:29.353+02:00")
      .up()
      .up()
      .ele("DOCUMENT_CREATOR")
      .ele("FIRST_NAME")
      .txt("Exporter")
      .up()
      .ele("LAST_NAME")
      .txt("openQ-CAT")
      .up()
      .ele("PHONE")
      .txt("+49.911.179")
      .up()
      .ele("ID_DB")
      .txt("nr:9354")
      .up()
      .ele("ADDRESS")
      .ele("NAME")
      .txt("IT-Systemhaus")
      .up()
      .ele("STREET")
      .txt("Regensburgerstr. 104")
      .up()
      .ele("ZIP")
      .txt("90478")
      .up()
      .ele("CITY")
      .txt("Nürnberg")
      .up()
      .ele("COUNTRY")
      .txt("DE")
      .up()
      .ele("URL")
      .txt("http://www.kursnet-online.arbeitsagentur.de")
      .up()
      .ele("ID_DB")
      .txt("adr:160")
      .up()
      .up()
      .ele("CONTACT_REMARKS")
      .txt("Eugen Riske")
      .up()
      .up()
      .ele("RECIPIENT")
      .ele("RECIPIENT_ID")
      .txt("BA")
      .up()
      .ele("RECIPIENT_NAME")
      .txt("Informationssystem KURSNET")
      .up()
      .ele("ADDRESS")
      .ele("NAME")
      .txt("IT-Systemhaus")
      .up()
      .ele("STREET")
      .txt("Regensburgerstr. 104")
      .up()
      .ele("ZIP")
      .txt("90478")
      .up()
      .ele("CITY")
      .txt("Nürnberg")
      .up()
      .ele("COUNTRY")
      .txt("DE")
      .up()
      .ele("URL")
      .txt("http://www.kursnet-online.arbeitsagentur.de")
      .up()
      .up()
      .up()
      .ele("SUPPLIER")
      .ele("SUPPLIER_ID", { type: "supplier_specific" })
      .txt("90037")
      .up()
      .ele("SUPPLIER_NAME")
      .txt("EuBiA Europäische Bildungsakademie Bildung / Perspektive / Erfolg")
      .up()
      .ele("ADDRESS")
      .ele("NAME")
      .txt("EuBiA")
      .up()
      .ele("NAME2")
      .txt("Europäische Bildungsakademie")
      .up()
      .ele("NAME3")
      .txt("Bildung / Perspektive / Erfolg")
      .up()
      .ele("STREET")
      .txt("Graf-Adolf-Straße 108")
      .up()
      .ele("ZIP")
      .txt("40210")
      .up()
      .ele("CITY")
      .txt("Düsseldorf")
      .up()
      .ele("STATE")
      .txt("Nordrhein-Westfalen")
      .up()
      .ele("COUNTRY")
      .txt("deutschland")
      .up()
      .ele("PHONE")
      .txt("+49.211.91382918")
      .up()
      .ele("MOBILE")
      .txt("")
      .up()
      .ele("FAX")
      .txt("+49.211.91382939")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("info@eubia.de")
      .up()
      .up()
      .ele("URL")
      .txt("http://www.eubia.de")
      .up()
      .ele("ID_DB")
      .txt("QLADR.16223")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "5" })
      .txt("Sonstige")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Kabri")
      .up()
      .ele("LAST_NAME")
      .txt("Hafida")
      .up()
      .ele("PHONE")
      .txt("+49.211.91382910")
      .up()
      .ele("MOBILE")
      .txt("")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("verwaltung@eubia.de")
      .up()
      .up()
      .ele("URL")
      .txt("http://www.eubia.de")
      .up()
      .ele("ID_DB")
      .txt("422987")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "5" })
      .txt("Sonstige")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Dörthe")
      .up()
      .ele("LAST_NAME")
      .txt("Stosberg")
      .up()
      .ele("PHONE")
      .txt("+49.451.20271240")
      .up()
      .ele("MOBILE")
      .txt("")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("d.stosberg@eubia.de")
      .up()
      .up()
      .ele("URL")
      .txt("http://www.eubia.de")
      .up()
      .ele("ID_DB")
      .txt("861773")
      .up()
      .ele("ADDRESS")
      .ele("NAME")
      .txt("EuBiA GmbH Lübeck")
      .up()
      .ele("STREET")
      .txt("Schüsselbuden 30-32")
      .up()
      .ele("ZIP")
      .txt("23552")
      .up()
      .ele("CITY")
      .txt("Lübeck")
      .up()
      .ele("STATE")
      .txt("Schleswig-Holstein")
      .up()
      .ele("COUNTRY")
      .txt("deutschland")
      .up()
      .ele("ADDRESS_REMARKS")
      .txt("Innenstadt Lübeck")
      .up()
      .up()
      .ele("CONTACT_REMARKS")
      .txt("Teamleitung")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "5" })
      .txt("Sonstige")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Ouassima")
      .up()
      .ele("LAST_NAME")
      .txt("Kayhan")
      .up()
      .ele("PHONE")
      .txt("+49.162.2638086")
      .up()
      .ele("MOBILE")
      .txt("")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("o.kayhan@eubia.de")
      .up()
      .up()
      .ele("ID_DB")
      .txt("1180770")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "5" })
      .txt("Sonstige")
      .up()
      .ele("SALUTATION")
      .txt("m")
      .up()
      .ele("FIRST_NAME")
      .txt("Mohamed")
      .up()
      .ele("LAST_NAME")
      .txt("Bentourqi")
      .up()
      .ele("PHONE")
      .txt("+49.211.91382916")
      .up()
      .ele("MOBILE")
      .txt("")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("m.bentourqi@eubia.de")
      .up()
      .up()
      .ele("URL")
      .txt("https://eubia.de/")
      .up()
      .ele("ID_DB")
      .txt("1221873")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("Verwaltung BSK und IK Düsseldorf")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "5" })
      .txt("Sonstige")
      .up()
      .ele("SALUTATION")
      .txt("m")
      .up()
      .ele("FIRST_NAME")
      .txt("Michael")
      .up()
      .ele("LAST_NAME")
      .txt("Syleounis")
      .up()
      .ele("PHONE")
      .txt("+49.211.54553884")
      .up()
      .ele("MOBILE")
      .txt("")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("m.syleounis@eubia.de")
      .up()
      .up()
      .ele("ID_DB")
      .txt("1053669")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "2" })
      .txt("Gesamtansprechpartner")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Tea")
      .up()
      .ele("LAST_NAME")
      .txt("Gadrani")
      .up()
      .ele("PHONE")
      .txt("+49.211.91382924")
      .up()
      .ele("MOBILE")
      .txt("")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("t.gadrani@eubia.de")
      .up()
      .up()
      .ele("ID_DB")
      .txt("1147367")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("Auszubildende")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "5" })
      .txt("Sonstige")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Julia")
      .up()
      .ele("LAST_NAME")
      .txt("Mischketat")
      .up()
      .ele("PHONE")
      .txt("+49.211.91382911")
      .up()
      .ele("MOBILE")
      .txt("")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("j.mischketat@eubia.de")
      .up()
      .up()
      .ele("ID_DB")
      .txt("1100892")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "5" })
      .txt("Sonstige")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Theresa")
      .up()
      .ele("LAST_NAME")
      .txt("Krause")
      .up()
      .ele("PHONE")
      .txt("+49.30.42141103")
      .up()
      .ele("MOBILE")
      .txt("+49.173.6089739")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("l.krause@eubia.de")
      .up()
      .up()
      .ele("URL")
      .txt("http://www.eubia.de")
      .up()
      .ele("ID_DB")
      .txt("1113951")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "2" })
      .txt("Gesamtansprechpartner")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Tatjana")
      .up()
      .ele("LAST_NAME")
      .txt("Miller")
      .up()
      .ele("PHONE")
      .txt("+49.211.91382916")
      .up()
      .ele("MOBILE")
      .txt("+49.173.9176041")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("t.miller@eubia.de")
      .up()
      .up()
      .ele("URL")
      .txt("http://www.eubia.de")
      .up()
      .ele("ID_DB")
      .txt("1222030")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("Fachbereichsleitung Sprachkursbereich")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "2" })
      .txt("Gesamtansprechpartner")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Nadine Desiree")
      .up()
      .ele("LAST_NAME")
      .txt("Frings")
      .up()
      .ele("PHONE")
      .txt("+49.211.91382910")
      .up()
      .ele("MOBILE")
      .txt("+49.160.2429560")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("n.frings@iwq-holding.de")
      .up()
      .up()
      .ele("ID_DB")
      .txt("1250575")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "2" })
      .txt("Gesamtansprechpartner")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Ulrike")
      .up()
      .ele("LAST_NAME")
      .txt("Rozman")
      .up()
      .ele("PHONE")
      .txt("+49.211.91382919")
      .up()
      .ele("MOBILE")
      .txt("")
      .up()
      .ele("FAX")
      .txt("+49.211.91382939")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("u.rozman@eubia.de")
      .up()
      .up()
      .ele("URL")
      .txt("http://www.eubia.de")
      .up()
      .ele("ID_DB")
      .txt("1086152")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("Montag bis Donnerstag von 09:00 Uhr bis 13:00 Uhr")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "5" })
      .txt("Sonstige")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Verena")
      .up()
      .ele("LAST_NAME")
      .txt("Del Castello")
      .up()
      .ele("PHONE")
      .txt("+49.231.98340480")
      .up()
      .ele("MOBILE")
      .txt("")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("dortmund@eubia.de")
      .up()
      .up()
      .ele("ID_DB")
      .txt("856774")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "5" })
      .txt("Sonstige")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Ekaterina")
      .up()
      .ele("LAST_NAME")
      .txt("Shchednova-Matschke")
      .up()
      .ele("PHONE")
      .txt("+49.211.9138291")
      .up()
      .ele("MOBILE")
      .txt("")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("e.shchednova-matschke@eubia.de")
      .up()
      .up()
      .ele("ID_DB")
      .txt("1221265")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("Schnittstelle Qualli.life")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "2" })
      .txt("Gesamtansprechpartner")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Irina")
      .up()
      .ele("LAST_NAME")
      .txt("Müller")
      .up()
      .ele("PHONE")
      .txt("+49.234.54683210")
      .up()
      .ele("MOBILE")
      .txt("+49.151.2916932")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("i.mueller@eubia.de")
      .up()
      .up()
      .ele("URL")
      .txt("http://www.eubia.de")
      .up()
      .ele("ID_DB")
      .txt("1222120")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("Verwaltung IK / BSK Bochum")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "3" })
      .txt("Leiter des Betriebs")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Fabienne")
      .up()
      .ele("LAST_NAME")
      .txt("Reher")
      .up()
      .ele("PHONE")
      .txt("+49.234.54683210")
      .up()
      .ele("MOBILE")
      .txt("+49.152.53297179")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("f.reher@eubia.de")
      .up()
      .up()
      .ele("URL")
      .txt("http://www.eubia.de")
      .up()
      .ele("ID_DB")
      .txt("1245178")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "5" })
      .txt("Sonstige")
      .up()
      .ele("SALUTATION")
      .txt("m")
      .up()
      .ele("FIRST_NAME")
      .txt("Rachid")
      .up()
      .ele("LAST_NAME")
      .txt("Debdoubi")
      .up()
      .ele("PHONE")
      .txt("+49.211.91382910")
      .up()
      .ele("MOBILE")
      .txt("")
      .up()
      .ele("FAX")
      .txt("+49.211.91382939")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("r.debdoubi@eubia.de")
      .up()
      .up()
      .ele("URL")
      .txt("http://www.eubia.de")
      .up()
      .ele("ID_DB")
      .txt("439593")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("")
      .up()
      .up()
      .ele("CONTACT")
      .ele("CONTACT_ROLE", { type: "5" })
      .txt("Sonstige")
      .up()
      .ele("SALUTATION")
      .txt("w")
      .up()
      .ele("FIRST_NAME")
      .txt("Nadine Desiree")
      .up()
      .ele("LAST_NAME")
      .txt("Frings")
      .up()
      .ele("PHONE")
      .txt("+49.211.91382910")
      .up()
      .ele("MOBILE")
      .txt("")
      .up()
      .ele("FAX")
      .txt("")
      .up()
      .ele("EMAILS")
      .ele("EMAIL")
      .txt("n.frings@iwq-holding.de")
      .up()
      .up()
      .ele("ID_DB")
      .txt("QLPERS.33698")
      .up()
      .ele("CONTACT_REMARKS")
      .txt("")
      .up()
      .up()
      .ele("KEYWORD")
      .txt("Erfolg")
      .up()
      .ele("KEYWORD")
      .txt("Bildung")
      .up()
      .ele("KEYWORD")
      .txt("EuBiA")
      .up()
      .ele("KEYWORD")
      .txt("EuBiA Europäische Bildungsakademie Bildung / Perspektive / Erfolg")
      .up()
      .ele("KEYWORD")
      .txt("Bildungsakademie")
      .up()
      .ele("KEYWORD")
      .txt("Perspektive")
      .up()
      .ele("KEYWORD")
      .txt("Europäische")
      .up()
      .ele("EXTENDED_INFO", { input_type: "0" })
      .ele("ORGANIZATIONAL_FORM", { type: "2" })
      .txt("Private Bildungseinrichtung")
      .up()
      .up()
      .up()
      .up();

    const newCatalog = root.ele("NEW_CATALOG", { FULLCATALOG: "true" });

    combinations.forEach((combination) => {
      const service = newCatalog.ele("SERVICE", { mode: "new" });
      service
        .ele("PRODUCT_ID")
        .txt(this.courseType.product_id || "219624556")
        .up();
      service.ele("COURSE_TYPE").txt(this.courseType.course_type).up();
      service
        .ele("SUPPLIER_ID_REF", { type: "supplier_specific" })
        .txt(this.organizationSettings.supplier_id_ref)
        .up();
      const serviceDetails = service.ele("SERVICE_DETAILS");
      serviceDetails.ele("TITLE").txt(combination.title).up();
      serviceDetails
        .ele("DESCRIPTION_LONG")
        .txt(this.courseType.description_long)
        .up();
      serviceDetails
        .ele("SUPPLIER_ALT_PID")
        .txt(this.organizationSettings.supplier_alt_pid)
        .up();
      const contact = serviceDetails.ele("CONTACT");
      contact
        .ele("CONTACT_ROLE", { type: this.organizationSettings.contact_type })
        .txt(this.organizationSettings.contact_role)
        .up();
      contact.ele("SALUTATION").txt(this.organizationSettings.salutation).up();
      contact.ele("FIRST_NAME").txt(this.organizationSettings.first_name).up();
      contact.ele("LAST_NAME").txt(this.organizationSettings.last_name).up();
      contact.ele("PHONE").txt(this.organizationSettings.phone).up();
      contact.ele("MOBILE").txt("").up();
      contact
        .ele("EMAILS")
        .ele("EMAIL")
        .txt(this.organizationSettings.email)
        .up()
        .up();
      contact.ele("URL").txt(this.organizationSettings.url).up();
      contact
        .ele("CONTACT_REMARKS")
        .txt(this.organizationSettings.contact_remarks)
        .up()
        .up();
      const serviceDate = serviceDetails.ele("SERVICE_DATE");
      serviceDate.ele("START_DATE").txt(combination.date.start_date).up();
      serviceDate.ele("END_DATE").txt(combination.date.end_date).up();
      serviceDate
        .ele("DATE_REMARKS")
        .txt(this.courseType.date_remarks || "Einzelne Präsenztage vor Ort")
        .up()
        .up();
      const keywords = this.courseType.keywords_group
        .split(",")
        .map((keyword) => keyword.trim());
      keywords.forEach((keyword) => {
        serviceDetails.ele("KEYWORD").txt(keyword).up();
      });
      serviceDetails
        .ele("TARGET_GROUP")
        .ele("TARGET_GROUP_TEXT")
        .txt(this.courseType.target_group_text)
        .up()
        .up();
      serviceDetails
        .ele("TERMS_AND_CONDITIONS")
        .txt(this.courseType.terms_and_conditions)
        .up();
      const serviceModule = serviceDetails.ele("SERVICE_MODULE");
      const education = serviceModule.ele("EDUCATION", {
        type: this.courseType.type,
      });
      education.ele("COURSE_ID").txt(this.course.course_id).up();
      const degree = education.ele("DEGREE", {
        type: this.courseType.degree_type1,
      });
      degree.ele("DEGREE_TITLE").txt(this.courseType.degree_title).up();
      degree
        .ele("DEGREE_EXAM", { type: this.courseType.degree_type2 })
        .ele("EXAMINER")
        .txt(this.courseType.examiner)
        .up()
        .up();
      degree
        .ele("DEGREE_ADD_QUALIFICATION")
        .txt(this.courseType.degree_add_qualification)
        .up();
      degree
        .ele("DEGREE_ENTITLED")
        .txt(this.courseType.degree_entitled)
        .up()
        .up();
      education.ele("SUBSIDY").txt(this.courseType.subsidy_description).up();
      education
        .ele("REGISTRATION_DATE")
        .txt(this.course.registration_date || "2024-06-24T00:00:00.000+02:00")
        .up();
      const mimeInfo = education.ele("MIME_INFO");
      mimeInfo
        .ele("MIME_ELEMENT")
        .ele("MIME_SOURCE")
        .txt(this.organizationSettings.mime_source)
        .up()
        .up();
      const certificate = education.ele("CERTIFICATE");
      certificate
        .ele("CERTIFICATE_STATUS")
        .txt(this.organizationSettings.certificate_status)
        .up();
      certificate
        .ele("CERTIFIER_NUMBER")
        .txt(this.organizationSettings.certifier_number)
        .up();
      certificate.ele("CERT_VALIDITY").up().up();
      const extendedInfo = education.ele("EXTENDED_INFO");
      extendedInfo
        .ele("INSTITUTION", {
          type: this.organizationSettings.institution_type,
        })
        .txt(this.organizationSettings.institution)
        .up();
      extendedInfo
        .ele("INSTRUCTION_FORM", { type: this.courseType.instruction_type1 })
        .txt(this.courseType.instruction_form_name)
        .up();
      extendedInfo
        .ele("EDUCATION_TYPE", { type: this.courseType.education_type2 })
        .txt(this.courseType.education_type2_name)
        .up()
        .up();
      const moduleCourse = education.ele("MODULE_COURSE");
      const location = moduleCourse.ele("LOCATION");
      location.ele("NAME").txt(this.organizationSettings.name).up();
      location.ele("NAME2").txt(this.organizationSettings.name2).up();
      location.ele("STREET").txt("Graf-Adolf-Str. 108").up();
      location.ele("ZIP").txt(combination.location.plz).up();
      location.ele("ZIPBOX").txt(combination.location.plz).up();
      location.ele("CITY").txt(combination.location.ort).up();
      location.ele("DISTRICT").txt("Innenstadt / Hauptbahnhof").up();
      location.ele("STATE").txt(combination.location.bundesland).up();
      location.ele("COUNTRY").txt(combination.location.land).up();
      location.ele("PHONE").txt(this.organizationSettings.phone).up();
      location.ele("FAX").txt(this.organizationSettings.fax).up();
      location
        .ele("EMAILS")
        .ele("EMAIL")
        .txt(this.organizationSettings.email)
        .up()
        .up();
      location.ele("URL").txt(this.organizationSettings.url).up();
      location.ele("ID_DB").txt("1086152").up();
      location
        .ele("ADDRESS_REMARKS")
        .txt(this.organizationSettings.contact_remarks)
        .up()
        .up();
      moduleCourse
        .ele("DURATION", { type: this.courseType.duration_type })
        .up();
      moduleCourse
        .ele("INSTRUCTION_REMARKS")
        .txt(this.courseType.instruction_remarks)
        .up();
      moduleCourse
        .ele("FLEXIBLE_START")
        .txt(this.courseType.flexible_start)
        .up();
      moduleCourse
        .ele("EXTENDED_INFO")
        .ele("SEGMENT_TYPE", { type: this.courseType.segment_type2 })
        .up()
        .up()
        .up();

      serviceDetails
        .ele("ANNOUNCEMENT")
        .ele("START_DATE")
        .txt(combination.date.start_date)
        .up()
        .ele("END_DATE")
        .txt(combination.date.end_date)
        .up()
        .up();
      service
        .ele("SERVICE_CLASSIFICATION")
        .ele("REFERENCE_CLASSIFICATION_SYSTEM_NAME")
        .txt("Kurssystematik")
        .up()
        .ele("FEATURE")
        .ele("FNAME")
        .txt(this.courseType.fname)
        .up()
        .ele("FVALUE")
        .txt(this.courseType.fvalue)
        .up()
        .up()
        .up();
      service
        .ele("SERVICE_PRICE_DETAILS")
        .ele("SERVICE_PRICE")
        .ele("PRICE_AMOUNT")
        .txt(this.courseType.price_amount)
        .up()
        .ele("PRICE_CURRENCY")
        .txt(this.courseType.price_currency)
        .up()
        .up()
        .up();
      service
        .ele("MIME_INFO")
        .ele("MIME_ELEMENT")
        .ele("MIME_SOURCE")
        .txt(
            this.organizationSettings.mime_source
        )
        .up()
        .up()
        .up();
    });

    return root.end({ prettyPrint: true });
  }
}

export default XmlHelper;
